### ISSUE TITLE
Issue running features in err.env / world.rb

### ISSUE THREAD

**Issue by gaffo** [cucumber/cucumber-rails#217]
I'm having the same issue:

Gemfile:

```
source 'https://rubygems.org'

gem 'rails', '3.2.3'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platform => :ruby

  gem 'uglifier', '>= 1.0.3'

    gem 'less-rails-bootstrap'
end

group :test, :cucumber do
  gem "test-unit"
    gem "execjs"
    gem "therubyracer"
    gem "autotest-rails"
    gem "autotest-notification"
    gem "mocha", :require => false
    gem "shoulda"
    gem "konacha"
    gem "capybara-webkit"
  gem "factory_girl_rails"
  gem "cucumber-rails", '~> 1.3.0', require: false
  gem 'database_cleaner'
  gem 'mainline'
end

gem 'jquery-rails'

gem 'rb-readline'

gem "devise"
gem "devise_invitable"
```

env.rb:

```
# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a 
# newer version of cucumber-rails. Consider adding your own code to a new file 
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'cucumber/rails'

# Capybara defaults to XPath selectors rather than Webrat's default of CSS3. In
# order to ease the transition to Capybara we set the default here. If you'd
# prefer to use XPath just remove this line and adjust any selectors in your
# steps to use the XPath syntax.
Capybara.default_selector = :css

# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail. This is a different from how 
# your application behaves in the production environment, where an error page will 
# be rendered instead.
#
# Sometimes we want to override this default behaviour and allow Rails to rescue
# exceptions and display an error page (just like when the app is running in production).
# Typical scenarios where you want to do this is when you test your error pages.
# There are two ways to allow Rails to rescue exceptions:
#
#1) Tag your scenario (or feature) with @allow-rescue
#
#2) Set the value below to true. Beware that doing this globally is not
# recommended as it will mask a lot of errors for you!
#
ActionController::Base.allow_rescue = false

# Remove/comment out the lines below if your app doesn't have a database.
# For some databases (like MongoDB and CouchDB) you may need to use :truncation instead.
begin
  DatabaseCleaner.strategy = :transaction
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

# You may also want to configure DatabaseCleaner to use different strategies for certain features and scenarios.
# See the DatabaseCleaner documentation for details. Example:
#
#   Before('@no-txn,@selenium,@culerity,@celerity,@javascript') do
#     # { :except => [:widgets] } may not do what you expect here
#     # as tCucumber::Rails::Database.javascript_strategy overrides
#     # this setting.
#     DatabaseCleaner.strategy = :truncation
#   end
#
#   Before('~@no-txn', '~@selenium', '~@culerity', '~@celerity', '~@javascript') do
#     DatabaseCleaner.strategy = :transaction
#   end
#

# Possible values are :truncation and :transaction
# The :transaction strategy is faster, but might give you threading problems.
# See https://github.com/cucumber/cucumber-rails/blob/master/features/choose_javascript_database_strategy.feature
Cucumber::Rails::Database.javascript_strategy = :truncation

```

cucumber.yml

```
<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags ~@wip"
%>
default: <%= std_opts %> features
wip: --tags @wip:3 --wip featur<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags ~@wip"
%>
default: <%= std_opts %> features
wip: --tags @wip:3 --wip features
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip

```

Error when running "bundle exec cucumber":

```
➜  moveatron git:(cucumber) ✗ bundle exec cucumber
Using the default profile...
0 scenarios
0 steps
0m0.000s
/home/mike/workspace-web/moveatron/vendor/ruby/1.9.1/gems/cucumber-rails-1.3.0/lib/cucumber/rails/world.rb:13:in `initialize': wrong number of arguments (1 for 0) (ArgumentError)
    from /home/mike/workspace-web/moveatron/vendor/ruby/1.9.1/gems/test-unit-2.5.1/lib/test/unit/testsuitecreator.rb:38:in `new'
    from /home/mike/workspace-web/moveatron/vendor/ruby/1.9.1/gems/test-unit-2.5.1/lib/test/unit/testsuitecreator.rb:38:in `append_test'
    from /home/mike/workspace-web/moveatron/vendor/ruby/1.9.1/gems/test-unit-2.5.1/lib/test/unit/testsuitecreator.rb:32:in `create'
    from /home/mike/workspace-web/moveatron/vendor/ruby/1.9.1/gems/test-unit-2.5.1/lib/test/unit/testcase.rb:131:in `suite'
    from /home/mike/workspace-web/moveatron/vendor/ruby/1.9.1/gems/test-unit-2.5.1/lib/test/unit/collector/descendant.rb:15:in `block in collect'
    from /home/mike/workspace-web/moveatron/vendor/ruby/1.9.1/gems/test-unit-2.5.1/lib/test/unit/collector/descendant.rb:14:in `each'
    from /home/mike/workspace-web/moveatron/vendor/ruby/1.9.1/gems/test-unit-2.5.1/lib/test/unit/collector/descendant.rb:14:in `collect'
    from /home/mike/workspace-web/moveatron/vendor/ruby/1.9.1/gems/test-unit-2.5.1/lib/test/unit/autorunner.rb:83:in `block in <class:AutoRunner>'
    from /home/mike/workspace-web/moveatron/vendor/ruby/1.9.1/gems/test-unit-2.5.1/lib/test/unit/autorunner.rb:369:in `[]'
    from /home/mike/workspace-web/moveatron/vendor/ruby/1.9.1/gems/test-unit-2.5.1/lib/test/unit/autorunner.rb:369:in `run'
    from /home/mike/workspace-web/moveatron/vendor/ruby/1.9.1/gems/test-unit-2.5.1/lib/test/unit/autorunner.rb:58:in `run'
    from /home/mike/workspace-web/moveatron/vendor/ruby/1.9.1/gems/test-unit-2.5.1/lib/test/unit.rb:330:in `block in <top (required)>'
```

error when running "bundle exec rake cucumber":

```
➜  moveatron git:(cucumber) ✗ rake cucumber
/usr/local/bin/ruby -S bundle exec cucumber  --profile default
Using the default profile...
0 scenarios
0 steps
0m0.000s
invalid option: --profile
Test::Unit automatic runner.
Usage: /home/mike/workspace-web/moveatron/vendor/ruby/1.9.1/bin/cucumber [options] [-- untouched arguments]
    -r, --runner=RUNNER              Use the given RUNNER.
                                     (c[onsole], e[macs], x[ml])
        --collector=COLLECTOR        Use the given COLLECTOR.
                                     (de[scendant], di[r], l[oad], o[bject]_space)
    -n, --name=NAME                  Runs tests matching NAME.
                                     (patterns may be used).
        --ignore-name=NAME           Ignores tests matching NAME.
                                     (patterns may be used).
    -t, --testcase=TESTCASE          Runs tests in TestCases matching TESTCASE.
                                     (patterns may be used).
        --ignore-testcase=TESTCASE   Ignores tests in TestCases matching TESTCASE.
                                     (patterns may be used).
        --[no-]priority-mode         Runs some tests based on their priority.
        --default-priority=PRIORITY  Uses PRIORITY as default priority
                                     (h[igh], i[mportant], l[ow], m[ust], ne[ver], no[rmal])
    -I, --load-path=DIR[:DIR...]     Appends directory list to $LOAD_PATH.
        --color-scheme=SCHEME        Use SCHEME as color scheme.
                                     (d[efault])
        --config=FILE                Use YAML fomat FILE content as configuration file.
        --order=ORDER                Run tests in a test case in ORDER order.
                                     (a[lphabetic], d[efined], r[andom])
        --max-diff-target-string-size=SIZE
                                     Shows diff if both expected result string size and actual result string size are less than or equal SIZE in bytes.
                                     (1000)
    -v, --verbose=[LEVEL]            Set the output level (default is verbose).
                                     (important-only, n[ormal], p[rogress], s[ilent], v[erbose])
        --[no-]use-color=[auto]      Uses color output
                                     (default is auto)
        --progress-row-max=MAX       Uses MAX as max terminal width for progress mark
                                     (default is auto)
        --no-show-detail-immediately Shows not passed test details immediately.
                                     (default is yes)
        --output-file-descriptor=FD  Outputs to file descriptor FD
        --                           Stop processing options so that the
                                     remaining options will be passed to the
                                     test.
    -h, --help                       Display this help.

Deprecated options:
        --console                    Console runner (use --runner).

rake aborted!
Command failed with status (1): [/usr/local/bin/ruby -S bundle exec cucumbe...]

Tasks: TOP => cucumber => cucumber:ok
(See full trace by running task with --trace)
```

**Comment by singh08avinash** [comment]
Hiiii
Actually My database_cleaner gem is not working in cucumber rails so, i want to update database_cleaner gem through console in ubuntu.
If anyone know how can i update my database_cleaner gem or what i have to run on console .

Thank you

**Comment by singh08avinash** [comment]
@xtrasimplicity thank you sir..

**Comment by singh08avinash** [comment]
@xtrasimplicity  for providing slack ..
