### ISSUE TITLE
`bundle exec rake` runs minitest with cucumber options and raises exception

### ISSUE THREAD

**Issue by pbollenbeck** [cucumber/cucumber-rails#252]
Probably an unintended side effect of extraction of autorun suppression into multi_test.

In your shell:

``` sh
rails new cuke-test
cd cuke-test
```

Edit `./Gemfile`

``` ruby
# [...]
gem 'cucumber-rails', require: false
gem 'database_cleaner'
```

Setup Cucumber and run tests

``` sh
bundle
rails g cucumber:install
rake db:create db:migrate db:test:prepare
bundle exec rake
```

Output:

``` sh
0 scenarios
0 steps
0m0.000s
/Users/pbollenbeck/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/minitest-4.7.5/lib/minitest/unit.rb:1037:in `block in process_args': invalid option: --profile (OptionParser::InvalidOption)
    from /Users/pbollenbeck/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/minitest-4.7.5/lib/minitest/unit.rb:1016:in `new'
    from /Users/pbollenbeck/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/minitest-4.7.5/lib/minitest/unit.rb:1016:in `process_args'
    from /Users/pbollenbeck/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/minitest-4.7.5/lib/minitest/unit.rb:1066:in `_run'
    from /Users/pbollenbeck/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/minitest-4.7.5/lib/minitest/unit.rb:1059:in `run'
    from /Users/pbollenbeck/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/minitest-4.7.5/lib/minitest/unit.rb:795:in `block in autorun'
```

Bundle:

``` sh
cuke-test % bundle show
Gems included by the bundle:
  * actionmailer (4.0.0)
  * actionpack (4.0.0)
  * activemodel (4.0.0)
  * activerecord (4.0.0)
  * activerecord-deprecated_finders (1.0.3)
  * activesupport (4.0.0)
  * arel (4.0.0)
  * atomic (1.1.10)
  * builder (3.1.4)
  * bundler (1.3.5)
  * capybara (2.1.0)
  * coffee-rails (4.0.0)
  * coffee-script (2.2.0)
  * coffee-script-source (1.6.3)
  * cucumber (1.3.3)
  * cucumber-rails (1.3.0)
  * database_cleaner (1.0.1)
  * diff-lcs (1.2.4)
  * erubis (2.7.0)
  * execjs (1.4.0)
  * gherkin (2.12.0)
  * hike (1.2.3)
  * i18n (0.6.4)
  * jbuilder (1.4.2)
  * jquery-rails (3.0.2)
  * json (1.8.0)
  * mail (2.5.4)
  * mime-types (1.23)
  * mini_portile (0.5.1)
  * minitest (4.7.5)
  * multi_json (1.7.7)
  * multi_test (0.0.1)
  * nokogiri (1.6.0)
  * polyglot (0.3.3)
  * rack (1.5.2)
  * rack-test (0.6.2)
  * rails (4.0.0)
  * railties (4.0.0)
  * rake (10.1.0)
  * rdoc (3.12.2)
  * sass (3.2.9)
  * sass-rails (4.0.0)
  * sdoc (0.3.20)
  * sprockets (2.10.0)
  * sprockets-rails (2.0.0)
  * sqlite3 (1.3.7)
  * thor (0.18.1)
  * thread_safe (0.1.0)
  * tilt (1.4.1)
  * treetop (1.4.14)
  * turbolinks (1.2.0)
  * tzinfo (0.3.37)
  * uglifier (2.1.1)
  * xpath (2.0.0)
```

Environment:
- Ruby 2.0.0-p247 (also fails in p195)
- Bundler 1.3.5
- Rails 4.0.0

**Comment by bjoerne2** [comment]
My solution is similar to yours, @wtfiwtz, but I had to change a few details, as Minitest changed their code a little bit and env.rb was too late. I added an initializer (config/initializers/suppress_minitest.rb) with this content:

    # This is taken from here: https://groups.google.com/forum/#!topic/cukes/VoLUFDbiNdc
    require 'minitest'
    
    module Minitest
      @@installed_at_exit = true
    end
