### ISSUE TITLE
ruby / cucumber tests failing after upgrade to ruby 2.3.1

### ISSUE THREAD

**Issue by stevelake** [cucumber/cucumber-rails#329]
I've installed ruby 2.3.1 on my Windows 10 PC and cucumber tests which were passing under ruby 1.9.3 are now failing to run. The messages I get are...
invalid option: --dotcucumber (OptionParser::InvalidOption)
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/options.rb:271:in `parse!'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/options.rb:56:in `parse'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/options.rb:349:in `merge_with_profile'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/options.rb:341:in `block in merge_profiles'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/options.rb:340:in `each'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/options.rb:340:in `merge_profiles'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/options.rb:280:in `parse!'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/configuration.rb:26:in `parse!'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:65:in `block in configuration'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:64:in `tap'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:64:in `configuration'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:29:in `execute!'
c:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
c:/Ruby23/bin/cucumber:23:in `load'
c:/Ruby23/bin/cucumber:23:in `<main>'

I've installed all the gems I had in my previous environment (having first resolved the certificate issues as described at https://gist.github.com/luislavena/f064211759ee0f806c88#installing-using-update-packages-new and https://github.com/rubygems/rubygems/issues/1745#issuecomment-253739579

**Comment by stevelake** [comment]
If it's any help, I've attached the output from 'gem list'
[gem_list_ruby2.3.1.txt](https://github.com/cucumber/cucumber-rails/files/543935/gem_list_ruby2.3.1.txt)

**Comment by stevelake** [comment]
Issue resolved: there was an obsolete entry (--dotcucumber features/.cucumber) in the defaults in our cucumber.yml file!
