### ISSUE TITLE
Can't boot cucumber on Travis CI

### ISSUE THREAD

**Issue by brauliobo** [cucumber/cucumber-rails#335]
https://travis-ci.org/coletivoEITA/noosfero/jobs/208003222

```
cannot load such file -- cucumber/rails/action_controller (LoadError)
/home/travis/build/coletivoEITA/noosfero/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/home/travis/build/coletivoEITA/noosfero/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/home/travis/build/coletivoEITA/noosfero/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/travis/build/coletivoEITA/noosfero/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/home/travis/build/coletivoEITA/noosfero/vendor/bundle/ruby/2.3.0/gems/cucumber-rails-1.4.5/lib/cucumber/rails.rb:8:in `<top (required)>'
/home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/travis/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/travis/build/coletivoEITA/noosfero/features/support/env.rb:3:in `<top (required)>'
/home/travis/build/coletivoEITA/noosfero/vendor/bundle/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/rb_support/rb_language.rb:95:in `load'
/home/travis/build/coletivoEITA/noosfero/vendor/bundle/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/rb_support/rb_language.rb:95:in `load_code_file'
/home/travis/build/coletivoEITA/noosfero/vendor/bundle/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime/support_code.rb:180:in `load_file'
/home/travis/build/coletivoEITA/noosfero/vendor/bundle/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime/support_code.rb:83:in `block in load_files!'
/home/travis/build/coletivoEITA/noosfero/vendor/bundle/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime/support_code.rb:82:in `each'
/home/travis/build/coletivoEITA/noosfero/vendor/bundle/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime/support_code.rb:82:in `load_files!'
/home/travis/build/coletivoEITA/noosfero/vendor/bundle/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime.rb:184:in `load_step_definitions'
/home/travis/build/coletivoEITA/noosfero/vendor/bundle/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/runtime.rb:42:in `run!'
/home/travis/build/coletivoEITA/noosfero/vendor/bundle/ruby/2.3.0/gems/cucumber-1.3.20/lib/cucumber/cli/main.rb:47:in `execute!'
/home/travis/build/coletivoEITA/noosfero/vendor/bundle/ruby/2.3.0/gems/cucumber-1.3.20/bin/cucumber:13:in `<top (required)>'
/home/travis/build/coletivoEITA/noosfero/vendor/bundle/ruby/2.3.0/bin/cucumber:22:in `load'
/home/travis/build/coletivoEITA/noosfero/vendor/bundle/ruby/2.3.0/bin/cucumber:22:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/travis/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.3.3/bin/bundle:22:in `load'
/home/travis/.rvm/gems/ruby-2.3.3/bin/bundle:22:in `<main>'
```

**Comment by brauliobo** [comment]
this fixed the issue: https://github.com/noosfero/noosfero/commit/b1ef14db6a7c462029f5f2a6a9e2ff8896ffaef8

Apparently it only for with the `test` environment
