### ISSUE TITLE
Upgrade to 4.1.0 breaks javascript version of a feature test

### ISSUE THREAD

**Issue by bunnymatic** [cucumber/cucumber-rails#490]
Upgrading to 4.1.0 from 3.1.2 breaks test that were previously running fine around a simple login feature.

I'm on Rails 6.1, capybara 3.33.0, cucumber 4.1.0 (previously 3.1.2) and as of this upgrade, the tests that execute a simple login (visit the login page, fill in username and password) started to fail but only when `@javascript` is turned on.  The server reports "invalid password".  

**Reproducing**
I don't have a simple repo to share to easily reproduce this but I wonder if you might know what behavior might have changed that would lead to this.  I'll include some code snippets here and try to build a dummy app where I can better show the problem.  

The basic feature looks like this:

```
Feature: As a user I can login

Background:
  Given an account has been created
  Given I visit the login page

Scenario: login with good info
  When I fill in valid credentials
  And I click "Sign In"
  Then I see that I'm logged in
  And I click on the first "sign out" link
  Then I see that I'm logged out

@javascript
Scenario: login with good info
  When I fill in valid credentials
  And I click "Sign In"
  Then I see that I'm logged in
```

The `fill in valid credentials` through a few steps boils down to
```
  fill_in('Username/Email', with: login)
  fill_in('Password', with: pass)
```

The first feature, with javascript turned off, works just fine.  The second does not.  The server which is validating the login reports `invalid user/pass combo`.  I've verified that the parameters sent down to the `UserSession` model are the same in both cases.  I'm using `authlogic` under the hood but that gem has *not* been upgraded.

The failure is that "Then I see that I'm logged in" fails because the user is not successfully logged in but only in the version with `@javascript` turned on.

Could this be something about authorization headers or something?

I'll let you know if I can get this together in a smaller shareable repo scenario.  But if you have any insights on where the problem might be, I'm happy to do some more digging.

**Expected behavior**
I expect the tests to pass as they do with the previous version (3.1.2)

**Your Environment**
 - cucumber 4.1.0 - note versions 3.1.2 and 3.2.0 both work just fine
 - Gemfile diff - i tried to upgrade stepwise until i saw the issue - but that was basically 3.1.2 => 3.2.0 => 4.1.0
 - Operating System and version: Mac Mojave 10.14.6
 - brew/ruby/bundler

**Motivation**

I'm trying to get this project up to the latest (v5.x) and this is not allowing that to happen.

**Additional context**
This is the Gemfile.lock diff between the success and failure.  You will notice I pinned capybara to make sure that upgrade did not affect things as well as pinning `cucumber`.

```
diff --git a/Gemfile.lock b/Gemfile.lock
index eed8fbc3..5fc9b962 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -91,7 +91,6 @@ GEM
       aws-sigv4 (~> 1.1)
     aws-sigv4 (1.1.3)
       aws-eventstream (~> 1.0, >= 1.0.2)
-    backports (3.17.2)
     better_errors (2.7.1)
       coderay (>= 1.0.0)
       erubi (>= 1.0.0)
@@ -152,32 +151,47 @@ GEM
     crack (0.4.3)
       safe_yaml (~> 1.0.0)
     crass (1.0.6)
-    cucumber (3.1.2)
-      builder (>= 2.1.2)
-      cucumber-core (~> 3.2.0)
-      cucumber-expressions (~> 6.0.1)
-      cucumber-wire (~> 0.0.1)
-      diff-lcs (~> 1.3)
-      gherkin (~> 5.1.0)
-      multi_json (>= 1.7.5, < 2.0)
-      multi_test (>= 0.1.2)
-    cucumber-core (3.2.1)
-      backports (>= 3.8.0)
-      cucumber-tag_expressions (~> 1.1.0)
-      gherkin (~> 5.0)
-    cucumber-expressions (6.0.1)
-    cucumber-rails (2.0.0)
-      capybara (>= 2.12, < 4)
-      cucumber (>= 3.0.2, < 4)
-      mime-types (>= 2.0, < 4)
+    cucumber (4.1.0)
+      builder (~> 3.2, >= 3.2.3)
+      cucumber-core (~> 7.1, >= 7.1.0)
+      cucumber-create-meta (~> 1.0.0, >= 1.0.0)
+      cucumber-cucumber-expressions (~> 10.1, >= 10.1.0)
+      cucumber-gherkin (~> 14.0, >= 14.0.1)
+      cucumber-html-formatter (~> 7.0, >= 7.0.0)
+      cucumber-messages (~> 12.2, >= 12.2.0)
+      cucumber-wire (~> 3.1, >= 3.1.0)
+      diff-lcs (~> 1.3, >= 1.3, < 1.4)
+      multi_test (~> 0.1, >= 0.1.2)
+      sys-uname (~> 1.0, >= 1.0.2)
+    cucumber-core (7.1.0)
+      cucumber-gherkin (~> 14.0, >= 14.0.1)
+      cucumber-messages (~> 12.2, >= 12.2.0)
+      cucumber-tag-expressions (~> 2.0, >= 2.0.4)
+    cucumber-create-meta (1.0.0)
+      cucumber-messages (~> 12.2, >= 12.2.0)
+      sys-uname (~> 1.2, >= 1.2.1)
+    cucumber-cucumber-expressions (10.3.0)
+    cucumber-gherkin (14.2.0)
+      cucumber-messages (~> 12.4, >= 12.4.0)
+    cucumber-html-formatter (7.2.0)
+      cucumber-messages (~> 12.4, >= 12.4.0)
+    cucumber-messages (12.4.0)
+      protobuf-cucumber (~> 3.10, >= 3.10.8)
+    cucumber-rails (2.2.0)
+      capybara (>= 2.18, < 4)
+      cucumber (>= 3.0.2, < 6)
+      mime-types (~> 3.2)
       nokogiri (~> 1.8)
-      railties (>= 4.2, < 7)
-    cucumber-tag_expressions (1.1.1)
-    cucumber-wire (0.0.1)
+      rails (>= 5.0, < 7)
+    cucumber-tag-expressions (2.0.4)
+    cucumber-wire (3.1.0)
+      cucumber-core (~> 7.1, >= 7.1.0)
+      cucumber-cucumber-expressions (~> 10.1, >= 10.1.0)
+      cucumber-messages (~> 12.2, >= 12.2.0)
     dalli (2.7.10)
     database_cleaner (1.8.5)
     debug_inspector (0.0.3)
-    diff-lcs (1.4.4)
+    diff-lcs (1.3)
     docile (1.3.2)
     dotenv (2.7.6)
     dotenv-rails (2.7.6)
@@ -224,7 +238,6 @@ GEM
     geokit-rails (2.3.1)
       geokit (~> 1.5)
       rails (>= 3.0)
-    gherkin (5.1.0)
     gibbon (3.3.4)
       faraday (>= 0.16.0)
       multi_json (>= 1.11.0)
@@ -270,9 +283,10 @@ GEM
     marcel (0.3.3)
       mimemagic (~> 0.3.2)
     method_source (1.0.0)
+    middleware (0.1.0)
     mime-types (3.3.1)
       mime-types-data (~> 3.2015)
-    mime-types-data (3.2020.0512)
+    mime-types-data (3.2020.1104)
     mimemagic (0.3.5)
     mini_mime (1.0.2)
     mini_portile2 (2.5.0)
@@ -304,7 +318,12 @@ GEM
     postmark-rails (0.20.0)
       actionmailer (>= 3.0.0)
       postmark (~> 1.15)
-    public_suffix (4.0.5)
+    protobuf-cucumber (3.10.8)
+      activesupport (>= 3.2)
+      middleware
+      thor
+      thread_safe
+    public_suffix (4.0.6)
     puma (4.3.5)
       nio4r (~> 2.0)
     qr4r (0.6.0)
@@ -366,7 +385,7 @@ GEM
     rdiscount (2.2.0.1)
     recaptcha (5.5.0)
       json
-    regexp_parser (1.7.1)
+    regexp_parser (1.8.2)
     request_store (1.5.0)
       rack (>= 1.4)
     require_all (3.0.0)
@@ -455,11 +474,14 @@ GEM
     sshkit (1.21.0)
       net-scp (>= 1.1.2)
       net-ssh (>= 2.8.0)
+    sys-uname (1.2.2)
+      ffi (~> 1.1)
     temple (0.8.2)
     terrapin (0.6.0)
       climate_control (>= 0.0.3, < 1.0)
     test-prof (0.11.3)
     thor (1.0.1)
+    thread_safe (0.3.6)
     tilt (2.0.10)
     tzinfo (2.0.4)
       concurrent-ruby (~> 1.0)
@@ -506,11 +528,11 @@ DEPENDENCIES
   capistrano-rails
   capistrano-rbenv
   capistrano3-puma
-  capybara
+  capybara (= 3.33.0)
   capybara-email
   capybara-screenshot
   capybara-select-2
-  cucumber
+  cucumber (= 4.1.0)
   cucumber-rails
   dalli
   database_cleaner
```

Not sure if this would also be helpful (probably not) but this is the test output
```
be cucumber features/users/logintrim.feature
Elasticsearch url: http://localhost:9250
Using the default profile...
Feature: As a user I can login

  Background:                         # features/users/logintrim.feature:3
Capybara starting Puma...
* Version 4.3.5 , codename: Mysterious Traveller
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:65316
    Given an account has been created # features/step_definitions/factory_steps.rb:3
    Given I visit the login page      # features/step_definitions/shared_steps.rb:73

  @javascript
  Scenario: login with good info             # features/users/logintrim.feature:15
    When I fill in valid credentials         # features/step_definitions/user_steps.rb:44
    And I click "Sign In"                    # features/step_definitions/shared_steps.rb:186
    Then I see that I'm logged in            # features/step_definitions/user_steps.rb:48
      execution expired (Timeout::Error)
      ./features/support/flash_message_matchers.rb:10:in `block (3 levels) in <top (required)>'
      ./features/support/capybara_helpers.rb:22:in `block (2 levels) in wait_until'
      ./features/support/capybara_helpers.rb:21:in `loop'
      ./features/support/capybara_helpers.rb:21:in `block in wait_until'
      ./features/support/capybara_helpers.rb:20:in `wait_until'
      ./features/support/flash_message_matchers.rb:9:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/user_steps.rb:49:in `/^I see that I'm logged in$/'
      ./features/support/capybara.rb:48:in `block in <top (required)>'
      features/users/logintrim.feature:18:in `I see that I'm logged in'
    And I click on the first "sign out" link # features/step_definitions/shared_steps.rb:218
    Then I see that I'm logged out           # features/step_definitions/user_steps.rb:61
    HTML screenshot: /Users/jon/projects/mau/tmp/capybara/screenshot_2021-01-09-14-07-40.520.html
    Image screenshot: /Users/jon/projects/mau/tmp/capybara/screenshot_2021-01-09-14-07-40.520.png

WARNING: #embed(file, mime_type, label) is deprecated and will be removed after version 5.0.0. Please use attach(file, media_type) instead.
(Called from /Users/jon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/capybara-screenshot-1.0.24/lib/capybara-screenshot/cucumber.rb:24:in `block (2 levels) in <top (required)>')

  Scenario: login with good info             # features/users/logintrim.feature:7
    When I fill in valid credentials         # features/step_definitions/user_steps.rb:44
    And I click "Sign In"                    # features/step_definitions/shared_steps.rb:186
    Then I see that I'm logged in            # features/step_definitions/user_steps.rb:48
    And I click on the first "sign out" link # features/step_definitions/shared_steps.rb:218
    Then I see that I'm logged out           # features/step_definitions/user_steps.rb:61

Failing Scenarios:
cucumber features/users/logintrim.feature:15 # Scenario: login with good info

2 scenarios (1 failed, 1 passed)
14 steps (1 failed, 2 skipped, 11 passed)
0m10.547s
```

**Comment by luke-hill** [comment]
This isn't a cucumber ruby issue, it'll be a cucumber rails cucumber ruby interop issue. As the tag functionality is purely covered in cucumber-rails.

The way to prove this is to strip down your repo to just cucumber ruby. And I posit you won't find the issue. Your capybara version may also have an effect on this, although given you're using a late version I doubt that.

I would also look into if the underlying method failure is fill_in (As you've not provided a stacktrace). If it is, then that's pure capybara. 

What driver are you using?
Is it purely switching from @javascript to without that causes the issue?

**Comment by luke-hill** [comment]
I've recently added some tests into this repo to test the JS Drivers more rigorously. Could you see if you get any failures in our repo? Or better yet, push a failing test to this repo?

Let me know how you get on @bunnymatic

**Comment by bunnymatic** [comment]
Yes - just removing `@javascript` causes the failure.
I'm using chrome with Selenium 
```
  Capybara::Selenium::Driver.new(app,
                                 browser: :chrome,
                                 args: ['--window-size=1400,1200'])
``` 
But I seem to recall trying with Firefox and having the same issue.  

I'll give it a try and will look more closely.  I still haven't be able to repro this outside of my large project repo.  I like your suggestions of trying to pare things down in hopes of finding the culprit.

I'll let you know if I make any progress here.

**Comment by bunnymatic** [comment]
@luke-hill I just came back to check out what you might have pushed and I can't find a reference to any repo.  Were you going to add a link to some repo that I could poke around with?
>I've recently added some tests into this repo to test the JS Drivers more rigorously. Could you see if you get any failures in our repo? Or better yet, push a failing test to this repo?

**Comment by bunnymatic** [comment]
I think your suspicion is correct - that this is likely *not* `cucumber-rails` directly.  I added logging to my sessions controller and at the ruby tier - in the server - when javascript is on, it fails and when it's not, it succeeds.

The controller does this
```
  def create
    logger.info("Creating session #{user_session_params}")
    @user_session = UserSession.new(user_session_params)
    logger.info("valid? #{@user_session.valid?}")
    if @user_session.save
      flash[:notice] = "You're in!"
      redirect_back_or_default root_url
    else
      logger.info("fail #{@user_session.errors.full_messages}")
      render :new
    end
  end
```

Excerpt from @javascript on test
```
method=GET path=/login format=html controller=UserSessionsController action=new status=200 duration=183.39 view=135.95 db=4.99
  CmsDocument Load (0.4ms)  SELECT `cms_documents`.* FROM `cms_documents` WHERE `cms_documents`.`page` = 'signup' AND `cms_documents`.`section` = 'signup' LIMIT 1
Creating session {"login"=>"bmatic", "password"=>"***********"}
  User Load (0.5ms)  SELECT `users`.* FROM `users` WHERE `users`.`login` = 'bmatic' LIMIT 1
valid? false
fail ["That username/password combination is wrong.  Try again."]

Excerpt from no `@javascript` test 
```
method=GET path=/login format=html controller=UserSessionsController action=new status=200 duration=34.23 view=29.07 db=3.92
  CmsDocument Load (0.3ms)  SELECT `cms_documents`.* FROM `cms_documents` WHERE `cms_documents`.`page` = 'signup' AND `cms_documents`.`section` = 'signup' LIMIT 1
Creating session {"login"=>"bmatic", "password"=>"***********"}
  User Load (0.3ms)  SELECT `users`.* FROM `users` WHERE `users`.`login` = 'bmatic' LIMIT 1
valid? true
```

So this is something in `user_session.save` that is failing.  It showed up after upgrading `cucumber-rails` (which for this run is now `cucumber = 5.3.0, cucumber-rails = 2.2.0`

In any case, I'm pretty sure this is not your issue.  Also I'm reading my notes and I think I meant to file this against `cucumber` root because it appeared after upgrading `cucumber` (not cucumber-rails necesarily).

I appreciate your digging in a bit and sorry to have mis filed.  I'm going to close this ticket and see if I can't figure out what's going on.  If I do, i'll definitely come back here and leave some notes.

**Comment by bunnymatic** [comment]
I found the problem.  It looks like the DatabaseCleaner strategy is not being honored.  I'm going to try to repro in a small repo.  But in my `env` i have

```
DatabaseCleaner.strategy = :transaction
Cucumber::Rails::Database.javascript_strategy = :truncation
```
which apparently has been working fine up to now. 
But with upgraded `cucumber = 5.3.0, cucumber-rails = 2.2.0` it seems that it's no longer working.  With this same set of configs, if I look at the `log/test.log` output it's clear that with the old libraries, it's truncating, and with the new ones it looks like it's using `transaction` for the `Background` and then maybe `truncation` for the `Scenario` which means my background setup data is locked up in the `transaction`.


Here are snippets from the log files: 

With the older gems (the working scenario):
  * cucumber (3.1.2)
  * cucumber-core (3.2.1)
  * cucumber-expressions (6.0.1)
  * cucumber-rails (2.0.0)
  * cucumber-tag_expressions (1.1.1)
  * cucumber-wire (0.0.1)
  * database_cleaner (1.8.5)  

``` 
# excerpt from log/test.log
   (0.3ms)  SELECT `ar_internal_metadata`.`value` FROM `ar_internal_metadata` WHERE `ar_internal_metadata`.`key` = 'schema_sha1'
   (0.3ms)  SELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC
Dalli::Server#connect 127.0.0.1:11211
   (0.4ms)  SELECT @@FOREIGN_KEY_CHECKS
   (0.2ms)  SET FOREIGN_KEY_CHECKS = 0
   (0.5ms)  select table_name from information_schema.views where table_schema = 'mau_test'
   (2.8ms)  TRUNCATE TABLE `application_events`;
   (1.9ms)  TRUNCATE TABLE `art_piece_tags`;
   (2.4ms)  TRUNCATE TABLE `art_pieces`;
   (2.4ms)  TRUNCATE TABLE `art_pieces_tags`;
 ...

# the background step is here where it creates an `Artist` record and commits it

   (0.2ms)  SET FOREIGN_KEY_CHECKS = 1
   (0.3ms)  SELECT `ar_internal_metadata`.`value` FROM `ar_internal_metadata` WHERE `ar_internal_metadata`.`key` = 'schema_sha1'
   (0.3ms)  SELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC
Dalli::Server#connect 127.0.0.1:11211
  Artist Load (0.3ms)  SELECT `users`.* FROM `users` WHERE `users`.`type` = 'Artist' AND `users`.`login` = 'bmatic' ORDER BY `users`.`id` ASC LIMIT 1
  TRANSACTION (0.3ms)  BEGIN
  User Exists? (0.3ms)  SELECT 1 AS one FROM `users` WHERE `users`.`id` IS NOT NULL AND `users`.`slug` = 'bmatic' LIMIT 1
  User Exists? (0.2ms)  SELECT 1 AS one FROM `users` WHERE `users`.`login` = 'bmatic' LIMIT 1
  User Exists? (0.2ms)  SELECT 1 AS one FROM `users` WHERE `users`.`email` = 'bmatic@example.com' LIMIT 1
  BlacklistDomain Load (0.2ms)  SELECT `blacklist_domains`.* FROM `blacklist_domains` WHERE `blacklist_domains`.`domain` = 'example.com' LIMIT 1
  User Exists? (0.2ms)  SELECT 1 AS one FROM `users` WHERE `users`.`persistence_token` = BINARY '7348d486bd53b59bddb1651fca461a51b29040c5c618e5562e45e48a65728ed282be19c72951d8dd730472914297d28a3f2cc4c1b73d0bcf6ac839d24952ee2c' LIMIT 1
  Artist Create (0.4ms)  INSERT INTO `users` (`login`, `email`, `crypted_password`, `password_salt`, `created_at`, `updated_at`, `firstname`, `lastname`, `nomdeplume`, `activation_code`, `activated_at`, `state`, `persistence_token`, `slug`, `links`) VALUES ('bmatic', 'bmatic@example.com', '400$8$42$a345beb83ecc9165$36616f3f40330d3d3e4bfd6750ddc3229e12ed6fe9df51290e5ede692d98e4e6', '44_nXxzim1bq9WWyjNqn', '2021-02-06 21:08:14', '2021-02-06 21:08:14', 'Irwin', 'Sherman', 'Williamson-Jones', '7aa4c5434b507fd820f236fef2642cdedc4bd299', '2021-02-06 20:08:14', 'active', '7348d486bd53b59bddb1651fca461a51b29040c5c618e5562e45e48a65728ed282be19c72951d8dd730472914297d28a3f2cc4c1b73d0bcf6ac839d24952ee2c', 'bmatic', '--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess\nwebsite: http://hodkiewicz.co/luther\n')
  TRANSACTION (1.3ms)  COMMIT

...

```
  
And from here the test runs fine.

After upgrading to 
  * cucumber (5.3.0)
  * cucumber-core (8.0.1)
  * cucumber-create-meta (2.0.4)
  * cucumber-cucumber-expressions (10.3.0)
  * cucumber-gherkin (15.0.2)
  * cucumber-html-formatter (9.0.0)
  * cucumber-messages (13.2.1)
  * cucumber-rails (2.2.0)
  * cucumber-tag-expressions (2.0.4)
  * cucumber-wire (4.0.1)
  * protobuf-cucumber (3.10.8)
  * database_cleaner (1.8.5)
  
```
# excerpt from log/test.log
   (0.3ms)  SELECT `ar_internal_metadata`.`value` FROM `ar_internal_metadata` WHERE `ar_internal_metadata`.`key` = 'schema_sha1'
   (0.3ms)  SELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC
Dalli::Server#connect 127.0.0.1:11211
  TRANSACTION (0.4ms)  BEGIN
  Artist Load (0.3ms)  SELECT `users`.* FROM `users` WHERE `users`.`type` = 'Artist' AND `users`.`login` = 'bmatic' ORDER BY `users`.`id` ASC LIMIT 1
  TRANSACTION (0.3ms)  SAVEPOINT active_record_1
  User Exists? (0.3ms)  SELECT 1 AS one FROM `users` WHERE `users`.`id` IS NOT NULL AND `users`.`slug` = 'bmatic' LIMIT 1
  User Exists? (0.2ms)  SELECT 1 AS one FROM `users` WHERE `users`.`login` = 'bmatic' LIMIT 1
  User Exists? (0.2ms)  SELECT 1 AS one FROM `users` WHERE `users`.`email` = 'bmatic@example.com' LIMIT 1
  BlacklistDomain Load (0.3ms)  SELECT `blacklist_domains`.* FROM `blacklist_domains` WHERE `blacklist_domains`.`domain` = 'example.com' LIMIT 1
  User Exists? (0.3ms)  SELECT 1 AS one FROM `users` WHERE `users`.`persistence_token` = BINARY '05f882952bf9e9dd3b7577c35f8bd5efa5d66adf5c299ba0b656f0ec993c3d9ff9b4dde5b4ccb225e839d527889f6723e8b6d9e680090a975487775345313932' LIMIT 1
  Artist Create (0.4ms)  INSERT INTO `users` (`login`, `email`, `crypted_password`, `password_salt`, `created_at`, `updated_at`, `firstname`, `lastname`, `nomdeplume`, `activation_code`, `activated_at`, `state`, `persistence_token`, `slug`, `links`) VALUES ('bmatic', 'bmatic@example.com', '400$8$42$b7903f60b7fdf3d4$09f0c0ca3e41a5b21c0c5f4c432460e08863959f1c2763463d2d7512192e29b4', 'R6jUkc3BsNXnWpJZTaCV', '2021-02-06 21:18:08', '2021-02-06 21:18:08', 'Jin', 'Mercy', 'Ebert-Walsh', '079333e61c4593a853479aafc72e5482510f30b9', '2021-02-06 20:18:08', 'active', '05f882952bf9e9dd3b7577c35f8bd5efa5d66adf5c299ba0b656f0ec993c3d9ff9b4dde5b4ccb225e839d527889f6723e8b6d9e680090a975487775345313932', 'bmatic', '--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess\nwebsite: http://oberbrunner-schmeler.biz/toby\n')
  TRANSACTION (0.2ms)  RELEASE SAVEPOINT active_record_1
  ArtPiece Load (0.4ms)  SELECT `art_pieces`.* FROM `art_pieces` WHERE `art_pieces`.`artist_id` = 1 ORDER BY `art_pieces`.`position` ASC, `art_pieces`.`created_at` DESC LIMIT 1

# Notice the `RELEASE SAVEPOINT` above here... which means the `Artist Create` line which is 
# setting up my data for the test gets lost.
#
# And the fact that this does *not* start out with a pile of `TRUNCATE` calls

...

# Then the `TRUNCATE` step happens only at the very end of the test (i presume in an After cleanup)

   (0.3ms)  SELECT @@FOREIGN_KEY_CHECKS
   (0.2ms)  SET FOREIGN_KEY_CHECKS = 0
   (0.6ms)  select table_name from information_schema.views where table_schema = 'mau_test'
   (3.5ms)  TRUNCATE TABLE `application_events`;
   (1.8ms)  TRUNCATE TABLE `art_piece_tags`;
   (2.2ms)  TRUNCATE TABLE `art_pieces`;
   ...
   (3.0ms)  TRUNCATE TABLE `users`;
   (0.2ms)  SET FOREIGN_KEY_CHECKS = 1
  TRANSACTION (0.2ms)  ROLLBACK
```

**Comment by bunnymatic** [comment]
I'm unable to repro in a small separate rails repo.  Not sure what this app is doing that's different.  Pretty frustrating.

I *did* find that if I just give up on `:transaction` for everything and set the strategy in `env.rb` to `:truncation` all the time, things work just fine.  So I'm just going to roll with that and give up on this.

Again, thanks for your input and time.  And keep up the good work on `cucumber-rails`.

**Comment by marnen** [comment]
@bunnymatic That makes sense. The JavaScript browser client won't have access to the same transaction in which the Cucumber Ruby process created the user account.

**Comment by bunnymatic** [comment]
I agree @marnen .  Totally makes sense.  What *doesn't* make sense is that before the upgrade the very same tests were working just fine.  So *something* about some of the bundle updates changed where/when `:transaction` was getting handled.  Not a big deal.  I certainly had fun (sort of) digging around in the codes. :D
