### ISSUE TITLE
Test::Unit automatic runner runs after cucumber features are done

### ISSUE THREAD

**Issue by rickmzp** [cucumber/cucumber-rails#88]
So my cucumber features run just fine, but once they've finished running it tries to start the Test::Unit auto runner. It fails when cucumber tries to pass it "--profile default" and Test::Unit complains that it's an invalid argument. That happens after running just "rake"

Now if I run "cucumber features", they run again just fine but then exits with:

```
/Users/rick/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/test/unit/testcase.rb:64:in `initialize': wrong number of arguments (1 for 0) (ArgumentError)
from /Users/rick/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/test/unit/testcase.rb:64:in `new'
from /Users/rick/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/test/unit/testcase.rb:64:in `suite'
from /Users/rick/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/test/unit/testcase.rb:63:in `catch'
from /Users/rick/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/test/unit/testcase.rb:63:in `suite'
from /Users/rick/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/test/unit/collector/objectspace.rb:25:in `collect'
from /Users/rick/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/test/unit/collector/objectspace.rb:23:in `each_object'
from /Users/rick/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/test/unit/collector/objectspace.rb:23:in `collect'
from /Users/rick/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/test/unit/autorunner.rb:58
from /Users/rick/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/test/unit/autorunner.rb:213:in `[]'
from /Users/rick/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/test/unit/autorunner.rb:213:in `run'
from /Users/rick/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/test/unit/autorunner.rb:12:in `run'
from /Users/rick/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/test/unit.rb:279
from /Users/rick/.rvm/gems/ruby-1.8.7-p302@mailerapp/bin/cucumber:19
```

Any ideas what might be going on there?

Thanks!

**Comment by singh08avinash** [comment]
Hiiii
Actually My database_cleaner gem is not working in cucumber rails so, i want to update database_cleaner gem through console in ubuntu.
If anyone know how can i update my database_cleaner gem or what i have to run on console .

Thank you..
